export const languages = [
  { value: 'English', label: 'English' },
  { value: 'French', label: 'Français' },
  { value: 'Spanish', label: 'Español' },
  { value: 'German', label: 'Deutsch' },
  { value: 'Italian', label: 'Italiano' },
  { value: 'Portuguese', label: 'Português' },
  { value: 'Dutch', label: 'Nederlands' },
  { value: 'Croatian', label: 'Hrvatski' },
  { value: 'Bosnian', label: 'Bosanski' },
  { value: 'Albanian', label: 'Shqip' },
  { value: 'Vietnamese', label: 'Tiếng Việt' },
  { value: 'Turkish', label: 'Türkçe' },
  { value: 'Persian', label: 'فارسی' },
  { value: 'Urdu', label: 'اردو' },
  { value: 'Greek', label: 'Ελληνικά' },
  { value: 'Polish', label: 'Polski' },
  { value: 'Czech', label: 'Čeština' },
  { value: 'Swedish', label: 'Svenska' },
  { value: 'Danish', label: 'Dansk' },
  { value: 'Norwegian', label: 'Norsk' },
  { value: 'Finnish', label: 'Suomi' },
  { value: 'Hungarian', label: 'Magyar' },
  { value: 'Romanian', label: 'Română' },
  { value: 'Hebrew', label: 'עברית' },
  { value: 'Swahili', label: 'Kiswahili' },
  { value: 'Malay', label: 'Bahasa Melayu' },
  { value: 'Indonesian', label: 'Bahasa Indonesia' },
  { value: 'Filipino', label: 'Filipino' },
  { value: 'Thai', label: 'ภาษาไทย' },
  { value: 'Malayalam', label: 'മലയാളം' },
  { value: 'Sinhala', label: 'සිංහල' },
  { value: 'Khmer', label: 'ខ្មែរ' },
  { value: 'Laotian', label: 'ລາວ' },
  { value: 'Georgian', label: 'ქართული' },
  { value: 'Icelandic', label: 'Íslenska' },
  { value: 'Slovak', label: 'Slovenčina' },
  { value: 'Catalan', label: 'Català' },
  { value: 'Basque', label: 'Euskara' },
  { value: 'Uzbek', label: 'Oʻzbek' },
  { value: 'Russian', label: 'Русский' },
  { value: 'Ukrainian', label: 'Українська' },
  { value: 'Bulgarian', label: 'Български' },
  { value: 'Serbian', label: 'Српски' },
  { value: 'Macedonian', label: 'Македонски' },
  { value: 'Kazakh', label: 'Қазақша' },
  { value: 'Chinese (Simplified)', label: '简体中文' },
  { value: 'Chinese (Traditional)', label: '繁體中文' },
  { value: 'Japanese', label: '日本語' },
  { value: 'Korean', label: '한국어' },
  { value: 'Thai', label: 'ไทย' },
  { value: 'Arabic', label: 'العربية' },
  { value: 'Hindi', label: 'हिन्दी' },
  { value: 'Bengali', label: 'বাংলা' },
  { value: 'Punjabi', label: 'ਪੰਜਾਬੀ' },
  { value: 'Kannada', label: 'ಕನ್ನಡ' },
  { value: 'Tamil', label: 'தமிழ்' },
  { value: 'Telugu', label: 'తెలుగు' },
  { value: 'Marathi', label: 'मराठी' },
  { value: 'Armenian', label: 'Հայերեն' },
];
